### ISSUE TITLE
Error doing Pip. Fix requirements 

### ISSUE THREAD

**Issue by zetteron** [tmb5cg/Fifa21-Autobidder#10]
![image](https://user-images.githubusercontent.com/48014790/114330457-73f12200-9b4a-11eb-8850-c9fcea07a5e5.png)

I believe you have missed something regarding anaconda project version.

**Comment by tmb5cg** [comment]
Hi are you sure python is installed properly? Try running a test.py file

**Comment by zetteron** [comment]
When i get back home i'll check and reply. what version of python are you running?

**Comment by tmb5cg** [comment]
3.7 I believe. Are you on Mac or pc? Looks like PC which is odd.

Did you originally install python via anaconda? Usually that can cause issues

**Comment by tmb5cg** [comment]
Try doing just 
pip install requirements.txt

**Comment by zetteron** [comment]
it doesn't work without -r on windows. 
The thing is-if i exclude anaconda and about 10-15 requirement titles pip runs fine. 
The old version worked fine but requirements had like 10 titles. 
Hello world and Car.py from pycharm website run fine.

**Comment by tmb5cg** [comment]
Hi I'm able to replicate the error. I'll let you know when it's fixed, thank you for pointing this out!

**Comment by tmb5cg** [comment]
The requirements.txt I uploaded wasn't from the venv, it literally pulled everything I had installed on my computer. Tysm for pointing this out I would've never noticed.

Just pushed the update, you'll notice there's only 6 requirements now... can't believe I didn't notice this. 

Let me know if it works for you now

**Comment by ch90045** [comment]
I am wondering why you use the anaconda dev environment rather a vanilla python. Do you need e.g. the "anaconda-client". Also quite at the end there are some packages which only exist for the mac os X branch - so i am curious how that should work with Windows. What i did was to globally replace "==" with ">=" so some of the quite old packages mentioned were satisfied with more up to date ones.

BTW, don't get me wrong - nice Autobidder!

**Comment by tmb5cg** [comment]
Hahah I appreciate it! Thanks
