### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by maxih4** [tmb5cg/Fifa21-Autobidder#11]
Hey,

did someone ever try to install it on a Windows device?
Cause for example the pyobjc is only available for mac os, so the installation of requirements.txt always fails.

**Comment by tmb5cg** [comment]
Woah good call. I only tested it on windows a couple versions ago, not recently.

I'll test the current version now!

**Comment by tmb5cg** [comment]
Thank you for pointing this out, I'm having issues on windows too. Will let you know when fixed

**Comment by tmb5cg** [comment]
Holy cow! The requirements.txt I uploaded wasn't from the venv, it literally pulled everything I had installed on my computer. Tysm for pointing this out I would've never noticed.

Please give the bot a try and it should work, curious to hear how it goes

**Comment by maxih4** [comment]
So is it now updated? Will give it a try tomorrow and let you know then

**Comment by tmb5cg** [comment]
Ya it is, redownload and you'll see new requirements.txt is nothing like the old one

**Comment by maxih4** [comment]
Now the installation works
