### ISSUE TITLE
Passthrough is not supported, GL is disabled

### ISSUE THREAD

**Issue by stanjaromin** [tmb5cg/Fifa21-Autobidder#13]
Hi, 
very often but not every time, I am getting this error:
[10352:20292:0426/164108.200:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled

Greetings!

**Comment by tmb5cg** [comment]
Hmmm that's a weird one... can you try updating chrome and redownloading chromedriver?
What type of computer are you using? Seems like a system issue but I could be wrong

**Comment by stanjaromin** [comment]
I will check this. Now I don't remember if it was before or after I changed the chromedriver. I am using a PC with W10.
