### ISSUE TITLE
Mass-bidding on Alphonso Davies - error

### ISSUE THREAD

**Issue by Hughesy** [tmb5cg/Fifa21-Autobidder#5]
I was mass bidding on Alphonso Davies and it started bidding on players which arent Davies. It also massively over bid on all of those cards by about 8k each. 

Did i do something wrong in setting it up?

**Comment by tmb5cg** [comment]
Oh no! Only use the autobidder on players with ONE version of their card - ie they can't have an in form or UCL, they just have a base card version.

Sorry this happened but please make sure to read the pop up notice when adding players (it says this exactly), or any pop up messages in general. 

I'm going to add a function that doesn't let the bot start if a player with multiple versions is added.. again sorry this happened

**Comment by Hughesy** [comment]
Haha I saw it and it didn't even register with me that he had more than one card 🙈. I will continue to test now

**Comment by Hughesy** [comment]
> Haha I saw it and it didn't even register with me that he had more than one card 🙈. I will continue to test now

I've now tried it with Jonny Evans, who only has one card. It bought 3 cards at 9900 each. Something funky is going on haha

**Comment by tmb5cg** [comment]
F

Can you upload your gui_logs.txt? 

And do you know if it bid the absurd amount while searching the TM or while on the watch list

**Comment by Hughesy** [comment]
[gui_logs.txt](https://github.com/tmb5cg/Fifa21-Autobidder/files/6103891/gui_logs.txt)

**Comment by Hughesy** [comment]
> F
> 
> Can you upload your gui_logs.txt?
> 
> And do you know if it bid the absurd amount while searching the TM or while on the watch list

it happened while on the tm. I was watching the webapp.

**Comment by tmb5cg** [comment]
Taking a look now, sorry again

**Comment by tmb5cg** [comment]
Can you send my player_list.txt? I've tried replicating this error so many times and never catch it. It looks like you were bidding on other players before Evans, did it bid properly on them and only happened to Evans or no

**Comment by Hughesy** [comment]
> Can you send my player_list.txt? I've tried replicating this error so many times and never catch it. It looks like you were bidding on other players before Evans, did it bid properly on them and only happened to Evans or no

I closed down the GUI and reopened, then deleted other players it bid on

[player_list.txt](https://github.com/tmb5cg/Fifa21-Autobidder/files/6103986/player_list.txt)

**Comment by tmb5cg** [comment]
About to push out a massive update that should fix all of this! Hope you'll give it another try... it won't look that much different but the backend is completely reworked and concurrent bot objects can't be created which is what caused the issue here

**Comment by Hughesy** [comment]
Yep happy to keep testing when you need! Let me know when you have pushed the update!

**Comment by tmb5cg** [comment]
Just uploaded... now it lets you know if the bot has stopped, when the Start Autobidder button pops back up.

So to stop the bot during its execution just interrupt and if it fights back (esp when searching for players) just fight some more and it'll eventually break.

Let me know if the bidding error happens

Also there's a feature that minimizes bid wars which could be good if you're not making much profit

**Comment by Hughesy** [comment]
I've been testing on and off over the last few weeks, and its seriously good! I cant really find many faults, and I can virtually leave it unwatched to do its thing! Good job and Thanks!

**Comment by tmb5cg** [comment]
That's awesome! Thanks man!
