### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by DMikhailiets** [tmb5cg/Fifa21-Autobidder#7]
Hi, thanks for your job man. I have this error in my terminal, after i click "Start autobidder" button. It was before last commit too.
[21:29:47] BidRound 0 | MIN: 700 MAX: 900

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "src/main.py", line 891, in run
    self.autobidder_reloaded.start()
  File "/home/user/My_Projects/Fifa21-Autobidder/src/autobidder.py", line 125, in start
    total_bids_made = self.helper.search_market_gather_players(cardname, max_price_to_pay, bidstomake_eachplayer, total_bids_made, "None", min_bid, max_bid)
  File "/home/user/My_Projects/Fifa21-Autobidder/src/helpers.py", line 236, in search_market_gather_players
    for card in players_on_page:
TypeError: 'NoneType' object is not iterable
[21:30:02] Exception getAllPlayerInfo

**Comment by tmb5cg** [comment]
Thanks man, as for terminal issues - if you see the ugly error message (like what you saw), it just means I didn't hide it with a Try/Except, usually for my own debugging 

I know what causes that issue it has to do with the getAllPlayerInfo (loads all players on the page so we know which ones to bid on), I believe there is a hard set sleep time to account for the page loading. 

My guess is that it took a bit longer to load than usual so getAllPlayerInfo returned nothing, ie NoneType when it tried analyzing the results. It's an easy fix so thanks for pointing it out (basically have the web driver actually do the waiting until the player results pop up)

Just hit the home button on the web app and click Start Autobidder again, let me know if it keeps happening

Also d

**Comment by tmb5cg** [comment]
Actually wait a sec did this happen after my most recent commit? Search_market_gather_players - I think is the new name of the search method

If so then I'll actually look deeper since it's an entirely new method

**Comment by tmb5cg** [comment]
I'm almost positive it's bc it took a bit longer than expected for the search results to pop up, would that make sense or do you think it's something diff 

Also let me know what you think of the new transfer listing method, it opens up new tabs with the Futbin URL's which is probably annoying if you're running the bot in the background 

I switched it to this (instead of fetching raw json by calling their endpoint) bc they got mad I called it too often while debugging so I can switch it back to the old method very easily

**Comment by DMikhailiets** [comment]
You're right. Problem with loading time, i increase sleep time end it work for me
